# Generated by Django 5.0 on 2024-03-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agv', '0004_alter_agv_capacite_alter_agv_vie_batterie'),
        ('blocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agv.agv')),
                ('id_bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocs.bloc')),
            ],
        ),
    ]
