# Generated by Django 5.0 on 2024-03-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
