# Generated by Django 4.1.13 on 2024-03-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_date_commande_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='time',
            field=models.TimeField(),
        ),
    ]
