# Generated by Django 5.0.3 on 2024-03-04 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agv', '0002_rename_nomagv_agv_nom_and_more'),
        ('blocs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('agv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agv.agv')),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocs.bloc')),
            ],
        ),
    ]
