# Generated by Django 5.0 on 2024-03-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
