# Generated by Django 4.1.13 on 2024-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_admin_id_alter_poste_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='poste',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
