# Generated by Django 4.1.13 on 2024-03-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_admin_alter_poste_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='poste',
            name='mac_address',
            field=models.CharField(default=34, max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
