# Generated by Django 5.0 on 2024-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAgv', models.CharField(max_length=100)),
                ('capacite', models.IntegerField()),
                ('vieBatterie', models.IntegerField()),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Porter une charge', 'Porter une charge'), ('Mise en charge', 'Mise en charge')], max_length=50)),
            ],
        ),
    ]
