# Generated by Django 5.0 on 2024-03-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agv',
            old_name='nomAgv',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='agv',
            old_name='vieBatterie',
            new_name='vie_batterie',
        ),
    ]
