# Generated by Django 5.0 on 2024-03-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agv', '0002_rename_nomagv_agv_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agv',
            name='status',
            field=models.CharField(choices=[('IN', 'Inactive'), ('PC', 'Porter une charge'), ('MC', 'Mise en charge')], max_length=50),
        ),
    ]
